### ISSUE TITLE
Example command?

### ISSUE THREAD

**Issue by abers** [BarraQDA/nvivotools#1]
First of all, a massive thanks for creating this repository.

I think I have the setup correctly but bit lost when running the scripts. However, not 100% sure if I am using the wrong arguments or whether its an issue with the SQL Server credentials. I managed to create a user but could not assign it as admin since SP_ADDSRVROLEMEMBER is not a stored procedure on the nvivo server instance.

Depending on how I write the arguments I either get a "Connection to the database failed for an unknown reason" error, "Adaptive Server is unavailable or does not exist" or an "Adaptive Server connection failed" error with the last one seeming to be in relation to a login failure. Say I had test.nvp what form would the argument take to specify it? 

Also pymssql does not install correctly through pip on the Raspberry Pi and results in a compile error (decided to try accessing the MSSQL server from RPi incase the errors were related to my Windows machine). Looks like the issue might apply to all arm processors requiring additional packages freetds-common and libsybdb5. May want to add to the instructions if that happens and they are using Debian based Linux distribution that they can install it instead via apt-get install python-pymssql or apt-get the two additional packages and then pip install pymssql. 

Cheers.

**Comment by abers** [comment]
Still not having any luck running the scripts but I made progress towards making the new user an admin. After adding the  ;-T7806 flag and running SQLCMD from the Binn folder to add a new admin user the correct commands are - with #comments from me:

CREATE LOGIN login_name with PASSWORD=’Password’ 
go 
#place single quotes around the password but not around the login_name as the 'help' page suggests

sp_addsvrolemember login_name,sysadmin 
go
#write the sp_ in lowercase not uppercase as the 'help' page suggests. Also note sysadmin is all lowercase and not with capital S as 'help' page suggests.

**Comment by jschultz** [comment]
Thanks for your interest and work on figuring out some of these glitches. Since I do have a raspberry pi at home I'll take a look at the pymssql issue you mention. 

Also on the MS SQL Server configuration - I vaguely remember having to do something like that. Really, I have no idea how anyone uses Microsoft when their configuration procedures are so complicated. I'll include your comments into the README - but also feel free to make your own fork and pull requests,  I promise to merge them promptly.
